language: node_js
services: mongodb
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - DROPBOX_CALLBACK_URL="http://localhost:8000/init/callback"
  - DROPBOX_CONNECT_URL="http://localhost:8000/init/connect"
  - DROPBOX_CLUESTR_ID="fake-app-id"
  - DROPBOX_CLUESTR_SECRET="fake-app-secret"
  - DROPBOX_TEST_CURSOR=""
  - secure: B/houGWoPcjRW34EAwSb7IH8eYl7Z9545y6wCl/gz8iZJ58iiW+htxQEBXqCRXKUb+60St11LmcReeqQNiINrxLQ67cjUyQ50BmkbBN+2oIFF4BvQxSLpca5pp6qhPQjHHpjVrAorPUS2OB1a6r5bMZo6MWCfUai/bMa7dG05zw=
  - secure: JIWeLN4hhITrysPw8ZA8X1VL1qKWAFUt9oxIDGiTltdCYMa7TzCq2a9vGQnqj3avHSOU4GHXOys+1XhegA3DO3Gu0F9jMSb8xWD4mPVPAoqQPErVStWLndH6YJeUVnu+qBfGLmGJCyUfsjs5lUUke/cGqD9S913nBwJnECSZMOE=
  - secure: dbZQKKi73TmxcGUEBvZXi8g3JwSAS9ivlokAe8e5PN0vvCJeivLLsamU+Tsvbt/r4l3JJT20Q5p0ErS5i7hcM2FpyWbLvjNa49VJtA1yengTU88kE2QIiDDWKrS7qklJKLJveO/IhZMSX4oFpPiKCeOkocoxc1hFKXB3ZO5fNk0=
  - secure: E0zplLguQZ0r8Ve0IuhC2iL2uDtuIPORuQDBGoZpc+14NfVbVrPfwS9K2aUyDU70e3o/CIi2eNyDPYEKui2SvTIeUILTxM2IlXUXo2M0M787KtoQiJSoip6SfwFbM9SwgGy4CIi+Z/dcUrrOol9nKCN5DUpzOvpRiOv0NyVDmgs=
  - secure: GNQIkQ3tNJQEilnxSS7QSSH3SqEPFkWEAjCkaKf7XpWbuqg07ncfZZ8UBJERdp8SsQZnFk+mBGH/IYOIiKlsapQrFSMv3J74L5Uf/jcv4dZTp2qQwSbdXBSg48HK6HWekhYaZA5Y4T0RNN0LaMwn+q/i7k5k2uOc9buk58p/z+E=
deploy:
  provider: heroku
  api_key:
    secure: S6qiV3HEkFwL8It2Jp5ICYNNLlZFu7KBuTvS6yFI2lheHlASBXjqfHS6h16i08hxAao6NG7bN8WnPJ4ITr3oJnUYOShJDPtJYVbPg2Uir/cmyfQQlaYgdvC0Cc61+J1NoKTh8ZOxcg2FZ0coIIJVzZGW40UGpEUb3oAH4ptu/sM=
  app: provider-dropbox
  on:
    repo: Papiel/provider-dropbox
