language: node_js
services: mongodb
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - DROPBOX_CALLBACK_URL="http://localhost:8000/init/callback"
  - DROPBOX_CONNECT_URL="http://localhost:8000/init/connect"
  - DROPBOX_CLUESTR_ID="fake-app-id"
  - DROPBOX_CLUESTR_SECRET="fake-app-secret"
  - DROPBOX_TEST_CURSOR="AAHGAZxS20rjQgBQVVulcPzUCYmNf2m1KUpcEmsWOFnhGFpdDhSSRIgG-WAQQeNLYxq51l5AJDDtfD1Fox6vytTP0gn7ou7PL6Z3cMs2IADgjo2ED-YYyVLwP9D5XXaDYQlQb5vEiOtfLPu3sxObDGseyveffqn03r8iotTvoI_-wlxMa0TrngZLKlAgF_xT2lGsdpDBIxiFLXXCG-CadZvA2_2ncaCJQTjJh7ODmQ4o7pU32kOEpHsBgB31PfUP4t0"
  - secure: B/houGWoPcjRW34EAwSb7IH8eYl7Z9545y6wCl/gz8iZJ58iiW+htxQEBXqCRXKUb+60St11LmcReeqQNiINrxLQ67cjUyQ50BmkbBN+2oIFF4BvQxSLpca5pp6qhPQjHHpjVrAorPUS2OB1a6r5bMZo6MWCfUai/bMa7dG05zw=
  - secure: JIWeLN4hhITrysPw8ZA8X1VL1qKWAFUt9oxIDGiTltdCYMa7TzCq2a9vGQnqj3avHSOU4GHXOys+1XhegA3DO3Gu0F9jMSb8xWD4mPVPAoqQPErVStWLndH6YJeUVnu+qBfGLmGJCyUfsjs5lUUke/cGqD9S913nBwJnECSZMOE=
  - secure: dbZQKKi73TmxcGUEBvZXi8g3JwSAS9ivlokAe8e5PN0vvCJeivLLsamU+Tsvbt/r4l3JJT20Q5p0ErS5i7hcM2FpyWbLvjNa49VJtA1yengTU88kE2QIiDDWKrS7qklJKLJveO/IhZMSX4oFpPiKCeOkocoxc1hFKXB3ZO5fNk0=
  - secure: E0zplLguQZ0r8Ve0IuhC2iL2uDtuIPORuQDBGoZpc+14NfVbVrPfwS9K2aUyDU70e3o/CIi2eNyDPYEKui2SvTIeUILTxM2IlXUXo2M0M787KtoQiJSoip6SfwFbM9SwgGy4CIi+Z/dcUrrOol9nKCN5DUpzOvpRiOv0NyVDmgs=
  - secure: GNQIkQ3tNJQEilnxSS7QSSH3SqEPFkWEAjCkaKf7XpWbuqg07ncfZZ8UBJERdp8SsQZnFk+mBGH/IYOIiKlsapQrFSMv3J74L5Uf/jcv4dZTp2qQwSbdXBSg48HK6HWekhYaZA5Y4T0RNN0LaMwn+q/i7k5k2uOc9buk58p/z+E=
