language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
script: npm test
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - ANYFETCH_API_ID="fake-app-id"
  - ANYFETCH_API_SECRET="fake-app-secret"
  - DROPBOX_TEST_CURSOR=""
  - DROPBOX_TEST_IMAGE_PATH="/neamarstamplittle.png"
  - secure: S9jTNgQkyn7cEIT4GrNjg/zB1zkK6a6/Zy9AxKRFKfKHOd0QOSqxDICiPnaztJyJpwiOTem0z/g1A3+6m1ZrMAfU4Koz2o/ZeLIavDImylC63D4y0BjDI1vQv/J/MHN+d5p3CLayXsXKRWlfFSpJXUpMqvJ4LPqWe04eFp5MoXE=
  - secure: UuZhCS5lbsvnqbmcg9OpDcAzC2+6jJaSIrY7XBfHJXaMPXHR6O+cuk++3xeFqGjjkzcIQACRmsbokGBgQZLsqBtYzxlnXaaWkPWlmuvzjrk8t+oVYNmuj4skhphkOVVSRgegio0BkNaqEXXypkkFC2NMnY05tFK0KH8MLz4c0RA=
  - secure: XHTwRLCgMGseXvDf5Ns9vs07Wdg43SIpjeKIJRzmtwkvjXUP5Dk0Y5/2O98eq3NnSZnCcH9W/Mj2/tZs3GTnkrTvE81Ys7KR3PQ7PJUr8wJqeNlQOPaLNwtQqcDM9ImZEjArh2KbsgYujmB8G6B9Sar8sULrXsG/OuSdflM+RVw=
  - secure: PgtfXcVwIiP3TVE/6lYcEvugSvzZAHu6S3hoT4GLwlph03/U1G5NkOwhnnJW8TircO3mnVJk8/OwxsCByNSp+W0Y0DwzLtOoga9tEwBkEtixFdoQUwB+O9LcOpOg2dKEwIjFQqoUWDoaGBc7fSrOLAc4Y7bho4lQck7sJZidv2k=
  - secure: h8NwpdJ4dKDwfCjS//kfrkQkrgqk5y0ObQPydB7BWk7xFPHzyc9zVV5ADgSlRckNBOuZcQpoGNbM8j1HDFqGN7lRvRZnj09MlApN5rGfnUQhAO2P4SHzcSZyrSMtQkr7WewbYNJ0k2VLAtjmod3Ny+QbcybbfXQg62YE+VNi05U=
deploy:
  provider: heroku
  api_key:
    secure: S6qiV3HEkFwL8It2Jp5ICYNNLlZFu7KBuTvS6yFI2lheHlASBXjqfHS6h16i08hxAao6NG7bN8WnPJ4ITr3oJnUYOShJDPtJYVbPg2Uir/cmyfQQlaYgdvC0Cc61+J1NoKTh8ZOxcg2FZ0coIIJVzZGW40UGpEUb3oAH4ptu/sM=
  app: anyfetch-provider-dropbox
  on:
    repo: Papiel/provider-dropbox
